### ISSUE TITLE
Can I execute example script with DreamEditBench dataset?

### ISSUE THREAD

**Issue by jm20041050** [DreamEditBenchTeam/DreamEdit#4]
I fixed the installation error and now downloading checkpoints.
Then I'm on prepare configuration file and have a question.

There are two types of dataset "src_img_data_folder_path" and "db_dataset_path" in configuration file (both tasks).
For the "src_img_data_folder_path", I thinks "addition_source" directory in DreamEditBench datasets can be an appropriate samples.
But there is no sample images for "db_dataset_path".

Where can I find samples for it?

**Comment by ltl3A87** [comment]
Hi, the 'db_dataset_path is the original subject' datasets from dreambooth, you can download it from https://github.com/google/dreambooth/tree/main/dataset.

**Comment by jm20041050** [comment]
@ltl3A87 Thanks a lot!
