### ISSUE TITLE
issue with python -m pip install -e GroundingDINO

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [DreamEditBenchTeam/DreamEdit#6]
I get this after running python -m pip install -e GroundingDINO :
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.[end of output]

**Comment by wenhuchen** [comment]
@vinesmsuic

**Comment by vinesmsuic** [comment]
Hi! This error looks like something to do with your g++ version. you might want to check your g++ version. 

I recommend using conda for your environment in that case installing will be much easier.
To install GroundingDINO-GPU:
```
which nvcc
nvcc --version
export BUILD_WITH_CUDA=True
export CUDA_HOME=$CONDA_PREFIX
echo $CUDA_HOME #you need  CUDA_HOME variable to run the installing script of GroundingDINO

pip install -e GroundingDINO
```
